export { default as Navbar } from './headerNavBar'
export {default as Hero } from './hero'
export {default as Footer} from './footer'
export {default as Projects} from './projects'
export {default as About} from './about'